# Generated by Django 4.0.3 on 2022-03-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sin_jim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='expiry_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
