# Generated by Django 4.0.3 on 2022-03-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sin_jim', '0002_alter_form_expiry_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantAnswers',
            new_name='ApplicantAnswer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='needed',
            new_name='is_required',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('test', 'test'), ('Descriptive', 'Descriptive')], max_length=300, null=True),
        ),
    ]
