# Generated by Django 4.0.3 on 2022-03-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sin_jim', '0003_rename_applicantanswers_applicantanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_type',
        ),
    ]
